spring:
  application:
    name: GateWay
  profiles:
    active: dev
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 60000
            response-timeout: 60000
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                - OPTIONS
                allowedHeaders: '*'
                allowCredentials: true
                maxAge: 36000
                allowedOriginPatterns:
                - '*'
          routes:
          - id: UserService
            uri: lb://UserService
            predicates:
            - Path=/api/user/**,/api/contact/**,/api/group/**
          - id: OfflineDataService
            uri: lb://OfflineDataService
            predicates:
            - Path=/api/message/**
          - id: AiService
            uri: lb://AiService
            predicates:
            - Path=/api/ai/**
          - id: RedPacketService
            uri: lb://RedPacketService
            predicates:
            - Path=/api/chat/redPacket/**
server:
  port: 10010
