spring:
  application:
    name: AiService
  profiles:
    active: dev
  mail:
    host: smtp.qq.com  # 以QQ邮箱为例
    port: 587
    username: xxxx # 你的发件账号
    password: xxxx # 你的SMTP授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8105
  servlet:
    context-path: /api

logging:
  level:
    dev.langchain4j.mcp: ERROR


langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: xxxxx
      streaming-chat-model:
        model-name: qwen-max
        api-key: xxxxx
      embedding-model:
        model-name: text-embedding-v4
        api-key: xxxxx


bigmodel:
  api-key: xxxxx


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always